name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Surge.sh
        run: npm install -g surge

      - name: Deploy to Surge.sh
        run: |
          surge --project ./ --domain ${{ secrets.SURGE_SUBDOMAIN }}.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
